# Generated by Django 5.1.2 on 2024-10-25 09:32

import commons.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.TextField()),
                ("shorted_url", models.CharField(db_index=True, max_length=5, unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(commons.models.base.CreatedAtColumnMixin, models.Model),
        ),
    ]
